name: Tests and Lint

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-versions: [ "3.9", "3.10", ]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-versions }}

    - name: Install tox and coverage
      run: pip install tox tox-gh-actions

    - name: Run Python tests
      run: make tests

    - name: Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV}}
        files: coverage.xml
        fail_ci_if_error: false
        verbose: true